config/routes.rb
Rails.application.routes.draw do

  resources :documents, only: [:new, :create, :index, :destroy]

  resources :pages

  root to: 'documents#index'

end

app/models/document.rb
class Document < ActiveRecord::Base

  has_many :pages, dependent: :destroy

  has_attached_file :asset, styles: { thumb: ["64x64", :png] } 

  validates_attachment :asset, content_type: {content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']}

  # after_pdf_post_process :convert_to_png
  
  process_in_background :asset

  after_asset_post_process :make_pages

  def destroy_attachments
    self.pages.each do |item|
      item.asset = nil
      item.save
    end
    self.asset = nil
    self.save
  end

  private

  def make_pages
    if valid?
      # Run ghostscript instead of ImageMagick to convert pdf to JPEG
      Paperclip.run('gs', "-dNOPAUSE -dBATCH -sDEVICE=jpeg -r100 -dUseCIEColor -o #{asset.queued_for_write[:original].path}-%d.jpeg #{asset.queued_for_write[:original].path}")
      # Paperclip.run('convert', "-quality #{Page::QUALITY} -density #{Page::DENSITY} #{asset.queued_for_write[:original].path} #{asset.queued_for_write[:original].path}%d.jpeg")
      images = Dir.glob("#{asset.queued_for_write[:original].path}*.jpeg").sort_by do |line|
        line.match(/(\d+)\.jpeg$/)[1].to_i
      end

      images.each do |page_image|
        pages.build(:asset => File.open(page_image))
      end
      FileUtils.rm images
    end
  end

  def convert_to_png
    # PostProcessUploadJob.perform_now(self.pdf.queued_for_write[:original].path)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base

  belongs_to :document

  has_attached_file :asset

  validates_attachment :asset, content_type: {content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf']}

  process_in_background :asset

  QUALITY = 100
  DENSITY = '80x80'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.order('created_at')
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params) 
    if @document.save
      flash[:success] = "The document was added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    document = Document.find(params[:id])
    document.destroy_attachments
    if document.destroy
      flash[:success] = "document deleted"
    else
      flash[:danger] = "Unable to delete document"
    end

    redirect_to documents_path
    
  end

  private

  def document_params
    params.require(:document).permit(:asset, :title, :id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @document = Document.find(params[:id])
    @pages = @document.pages
  end

  private

  def page_params
    params.require(:page).permit(:id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/_document.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(document.asset.url(:thumb), class: 'media-object'), pages_path(id: document.id) %>
    <%= form_for(document, :html => { :method => :delete}) do |f| %>
      <%= f.submit "delete" %>
    <% end %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= document.title %></h4>
  </div>
</div>

app/views/documents/index.html.erb
<div class="page-header"><h1>Documents</h1></div>
 
<%= render @documents %>

app/views/documents/new.html.erb
<div class="page-header"><h1>Upload Document</h1></div>
 
<%= form_for @document do |f| %>
  <%= render 'shared/errors', object: @document %>
 
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
 
  <div class="form-group">
    <%= f.label :asset %>
    <%= f.file_field :asset, class: 'form-control'%>
  </div>
 
  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PdfPngUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Simple Uploader', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Documents', root_path %></li>
        <li><%= link_to 'Upload Your Document', new_document_path %></li>
      </ul>
    </div>
  </div>
</nav>
 
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
 
  <%= yield %>
</div>

</body>
</html>

app/views/pages/_page.html.erb
<!-- <div class="media"> -->
<!--   <div class="media&#45;left"> -->
<!--     <%= link_to image_tag(page.asset.url, class: 'media&#45;object'), page.asset.url %> -->
<!--   </div> -->
<!-- </div> -->


  <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
    <a href=<%= page.asset.url %> itemprop="contentUrl" data-size="1024x1024">
        <img src=<%= page.asset.url %> itemprop="thumbnail" alt="Image description" />
    </a>
                                        <figcaption itemprop="caption description">Image caption  1</figcaption>
                                        
  </figure>

app/views/pages/index.html.erb
<div class="page-header"><h1>Pages</h1></div>


<div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">

  <%= render @pages %>
</div>


<!-- Root element of PhotoSwipe. Must have class pswp. -->
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

    <!-- Background of PhotoSwipe. 
         It's a separate element, as animating opacity is faster than rgba(). -->
    <div class="pswp__bg"></div>

    <!-- Slides wrapper with overflow:hidden. -->
    <div class="pswp__scroll-wrap">

        <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
        <!-- don't modify these 3 pswp__item elements, data is added later on. -->
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>

        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
        <div class="pswp__ui pswp__ui--hidden">

            <div class="pswp__top-bar">

                <!--  Controls are self-explanatory. Order can be changed. -->

                <div class="pswp__counter"></div>

                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                <!-- element will get class pswp__preloader--active when preloader is running -->
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                      <div class="pswp__preloader__cut">
                        <div class="pswp__preloader__donut"></div>
                      </div>
                    </div>
                </div>
            </div>

            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div> 
            </div>

            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
            </button>

            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
            </button>

            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>

          </div>

        </div>

</div>
<script type="text/javascript">
var initPhotoSwipeFromDOM = function(gallerySelector) {

    // parse slide data (url, title, size ...) from DOM elements 
    // (children of gallerySelector)
    var parseThumbnailElements = function(el) {
        var thumbElements = el.childNodes,
            numNodes = thumbElements.length,
            items = [],
            figureEl,
            linkEl,
            size,
            item;

        for(var i = 0; i < numNodes; i++) {

            figureEl = thumbElements[i]; // <figure> element

            // include only element nodes 
            if(figureEl.nodeType !== 1) {
                continue;
            }

            linkEl = figureEl.children[0]; // <a> element

            size = linkEl.getAttribute('data-size').split('x');

            // create slide object
            item = {
                src: linkEl.getAttribute('href'),
                w: parseInt(size[0], 10),
                h: parseInt(size[1], 10)
            };



            if(figureEl.children.length > 1) {
                // <figcaption> content
                item.title = figureEl.children[1].innerHTML; 
            }

            if(linkEl.children.length > 0) {
                // <img> thumbnail element, retrieving thumbnail url
                item.msrc = linkEl.children[0].getAttribute('src');
            } 

            item.el = figureEl; // save link to element for getThumbBoundsFn
            items.push(item);
        }

        return items;
    };

    // find nearest parent element
    var closest = function closest(el, fn) {
        return el && ( fn(el) ? el : closest(el.parentNode, fn) );
    };

    // triggers when user clicks on thumbnail
    var onThumbnailsClick = function(e) {
        e = e || window.event;
        e.preventDefault ? e.preventDefault() : e.returnValue = false;

        var eTarget = e.target || e.srcElement;

        // find root element of slide
        var clickedListItem = closest(eTarget, function(el) {
            return (el.tagName && el.tagName.toUpperCase() === 'FIGURE');
        });

        if(!clickedListItem) {
            return;
        }

        // find index of clicked item by looping through all child nodes
        // alternatively, you may define index via data- attribute
        var clickedGallery = clickedListItem.parentNode,
            childNodes = clickedListItem.parentNode.childNodes,
            numChildNodes = childNodes.length,
            nodeIndex = 0,
            index;

        for (var i = 0; i < numChildNodes; i++) {
            if(childNodes[i].nodeType !== 1) { 
                continue; 
            }

            if(childNodes[i] === clickedListItem) {
                index = nodeIndex;
                break;
            }
            nodeIndex++;
        }



        if(index >= 0) {
            // open PhotoSwipe if valid index found
            openPhotoSwipe( index, clickedGallery );
        }
        return false;
    };

    // parse picture index and gallery index from URL (#&pid=1&gid=2)
    var photoswipeParseHash = function() {
        var hash = window.location.hash.substring(1),
        params = {};

        if(hash.length < 5) {
            return params;
        }

        var vars = hash.split('&');
        for (var i = 0; i < vars.length; i++) {
            if(!vars[i]) {
                continue;
            }
            var pair = vars[i].split('=');  
            if(pair.length < 2) {
                continue;
            }           
            params[pair[0]] = pair[1];
        }

        if(params.gid) {
            params.gid = parseInt(params.gid, 10);
        }

        return params;
    };

    var openPhotoSwipe = function(index, galleryElement, disableAnimation, fromURL) {
        var pswpElement = document.querySelectorAll('.pswp')[0],
            gallery,
            options,
            items;

        items = parseThumbnailElements(galleryElement);

        // define options (if needed)
        options = {

            // define gallery index (for URL)
            galleryUID: galleryElement.getAttribute('data-pswp-uid'),

            getThumbBoundsFn: function(index) {
                // See Options -> getThumbBoundsFn section of documentation for more info
                var thumbnail = items[index].el.getElementsByTagName('img')[0], // find thumbnail
                    pageYScroll = window.pageYOffset || document.documentElement.scrollTop,
                    rect = thumbnail.getBoundingClientRect(); 

                return {x:rect.left, y:rect.top + pageYScroll, w:rect.width};
            }

        };

        // PhotoSwipe opened from URL
        if(fromURL) {
            if(options.galleryPIDs) {
                // parse real index when custom PIDs are used 
                // http://photoswipe.com/documentation/faq.html#custom-pid-in-url
                for(var j = 0; j < items.length; j++) {
                    if(items[j].pid == index) {
                        options.index = j;
                        break;
                    }
                }
            } else {
                // in URL indexes start from 1
                options.index = parseInt(index, 10) - 1;
            }
        } else {
            options.index = parseInt(index, 10);
        }

        // exit if index not found
        if( isNaN(options.index) ) {
            return;
        }

        if(disableAnimation) {
            options.showAnimationDuration = 0;
        }

        // Pass data to PhotoSwipe and initialize it
        gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
        gallery.init();
    };

    // loop through all gallery elements and bind events
    var galleryElements = document.querySelectorAll( gallerySelector );

    for(var i = 0, l = galleryElements.length; i < l; i++) {
        galleryElements[i].setAttribute('data-pswp-uid', i+1);
        galleryElements[i].onclick = onThumbnailsClick;
    }

    // Parse URL and open gallery if it contains #&pid=3&gid=1
    var hashData = photoswipeParseHash();
    if(hashData.pid && hashData.gid) {
        openPhotoSwipe( hashData.pid ,  galleryElements[ hashData.gid - 1 ], true, true );
    }
};

// execute above function
initPhotoSwipeFromDOM('.my-gallery');
</script>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>
 
    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>